import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    itemstyle: {
        width: '90%',
        height: 40,
    },
    boxx: {
        marginTop: 100,
        flex: 1,
        alignItems: 'center',
    },
    itemstyle: {
        backgroundColor: 'red',
        fontSize: 20,
    },
    picker: {
        width: '90%',
        backgroundColor: 'transparent',
        borderColor: 'red',
        borderWidth: 2,
        color: 'darkblue',
        fontSize: 50,

    },
    boxcont: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'darkblue',
        borderWidth: 2,
        marginTop: 20,
        borderRadius: 18,
    },
    boxconta: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'darkblue',
        borderWidth: 2,
        marginTop: 20,
        borderRadius: 18,
        textAlign: 'center',
        fontSize: 20,
    },
    boxcorner: {
        width: '90%',
        height: 60,
        backgroundColor: 'transparent',
        borderColor: 'darkblue',
        borderWidth: 2,
        marginTop: 20,
        borderRadius: 18,
        alignItems: 'center',
        justifyContent: 'center',
    },
    idan: {
        width: '80%',
        backgroundColor: 'darkblue',
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 15,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    idancover: {
        width: '100%',
        marginTop: 180,
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonin: {
        fontSize: 20,
        fontWeight: '700',
        color: 'white',
    },
    stopl: {
        textAlign: 'center',
        fontSize: 19,
        fontWeight: '400',
        color: 'black',
    },
    modalcontain: {
        flex: 1,
        justifyContent:'center',
        alignItems:'center',
        width:'100%',
      
    },
    modalcontent: {
        alignItems:'center',
        width:'90%',
        height:'auto',
        justifyContent:"space-around",
    },
    modaltext: {
        fontSize: 20,
        fontWeight: '700',
        color: 'darkblue',
        marginTop: 80,
        marginBottom: 40,
    },
    imgsrc:{
        width: 100,
        height: 100,
        backgroundColor: 'white',
        marginLeft: 10,
    }
})