import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({
    cert: {
        flex: 1,
        backgroundColor: 'white',
    },
    previewboxer: {
        flex: 1,
        backgroundColor: '#f5f5f5',
     
    },
    boxcont: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        alignItems: 'center',
        marginTop: 40,
    },
    container: {
        width: '60%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: 50,
        justifyContent: 'space-between',
        paddingRight:10,
        flexDirection:'row',
        alignItems: 'center',

    },
    buttonstyle: {
        width: '60%',
        backgroundColor: 'darkblue',
        borderRadius: 25,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        marginLeft:5,
        right: 0,
    },
    kilode: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
    free: {
        color: 'white',
        fontSize: 20,
        fontWeight: '500',
    },
  
    kiloder: {
        color: 'darkblue',
        fontSize: 20,
        fontWeight: '500',
    },
    image: {
        width: '100%',
        height: 200,
        marginTop: 50,
        borderRadius: 18,
    },
    free: {
        color: 'darkblue',
        fontSize: 35,
        fontWeight: '800',
        marginTop: 10,
        textAlign: 'center',
        fontFamily: 'sans-serif',
    },
    freer: {
        fontSize: 20,
        paddingLeft: 5,
        fontWeight: '700',
        marginTop: 10,
        textAlign: 'center',
    },
    textsmall:{
        color:'#696969',
        fontWeight:'600',
        paddingLeft:10,
        marginTop: 10,
    },
   
    creator:{
        color: 'darkblue',
        paddingLeft: 20,
        fontSize: 30,
        fontWeight: '700',
        marginTop: 120,
    },
    boxconter: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        marginTop: 50,
        alignItems: 'center',
    
    },
    boxconters: {
        width: '100%',
        borderRadius: 25,
        height: "auto",
        marginTop: 0,
        alignItems: 'center',
    
    },
    textcont:{
        flexDirection:'row',
        justifyContent:'space-around',
        margin: 0,
        borderRadius: 20,
        borderWidth: 1,
        borderRadius: 10,
        width: "80%",
        flexDirection: "row",
        alignItems:"center"
    },
    container: {
        paddingTop: 20,
        backgroundColor: 'red',
        alignItems: 'center',
        justifyContent: 'space-around',
        flex: 1,


    },
    boxxy: {
        height: '50%',

    },
    button: {
        backgroundColor: 'blue',
        borderRadius: 10,
        width: '50%',
        height: 30,
        alignItems: 'center',
        justifyContent: 'center',

    },
    input: {
        borderRadius: 10,
        borderWidth: 0.5,
        borderColor: 'black',
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 30,
        paddingRight: 30,
        color: 'black',
        margin: 10,
        backgroundColor: 'white',
    },
    inputs: {
        borderRadius: 5,
        borderWidth: 2,
        borderColor: 'black',
        paddingTop: 10,
        paddingBottom: 10,
        paddingLeft: 30,
        paddingRight: 30,
        color: 'black',
        margin: 10,
        fontSize:20,
    },
    create: {
        color: '#11053b',
        textAlign: 'center',
        fontSize: 25,
        fontWeight: '800',
        marginTop: 100,
        marginBottom: 10,
        fontFamily: 'inter',
    },
    textsmaller: {
        color: 'black',
        fontWeight: '600',
        paddingLeft: 10,
        textAlign: 'center',
        marginBottom: 20,
        fontSize: 18,
        fontFamily: 'inter-Medium',
    },
    hutton: {
        width: '80%',
        backgroundColor: '#11053b',
        borderWidth: 2,
        borderColor: 'white',
        borderRadius: 15,
        height: 45,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    press: {
        color: 'white',
        fontSize: 20,
        fontWeight: '700',
    },
    free: {
        fontSize: 20,
        fontWeight: '500',
        marginTop: 10,
        paddingLeft: 10,
        color: 'black',
    },
    idan: {
        color: 'black',
        fontSize:20,
        textAlign: 'center',
        fontFamily:'inter',
        fontWeight: '500',
        width:'90%',
    },
    idanm: {
        width: 40,
        height: 40,
        borderRadius: 30,
        backgroundColor: 'white',
        alignItems: 'center',
        justifyContent: 'center',
    },
    buttonin: {
        fontSize: 20,
        fontWeight: '500',
        marginTop: 10,
        color: 'red',
    },
    vowbox: {
        width: '90%',
        height: 200,
        backgroundColor: '#ffffff',
        alignItems: 'center',
        justifyContent: 'space-around',
        borderColor:'black',
        borderWidth:2,
        borderRadius:10,
    },
    textsmals: {
        color: 'black',
        fontWeight: '700',
        fontSize: 20,
        marginBottom:20,
    },

})