import { StyleSheet } from "react-native";
export const styles = StyleSheet.create({

    previewbox: {
        flex: 1,
        backgroundColor: 'white',
        alignItems: 'center',
        flexDirection: 'column',
        justifyContent: 'space-around',
        marginTop: 10,
    },
    buttonIcon: {
        paddingRight: 8,
    },
    dealer: {
        width: '90%',
        height: 300,
    },
    dealercover: {
        width: '100%',
        height: 300,
        backgroundColor: 'white',
        justifyContent: 'center',
        alignItems: 'center',
    },
    buttonstyle: {
        width: '70%',
        backgroundColor: '#11053b',
        borderRadius: 25,
        height: 40,
        alignItems: 'center',
        justifyContent: 'center',
        right: 0,
    },
    kilode: {
        color: 'white',
        fontSize: 18,
        fontWeight: '800',
    },
    boxcont: {
        width: '100%',
        borderRadius: 25,
        height: 70,
        position: 'absolute',
        alignItems: 'center',
        bottom: 19,
    },
    container: {
        width:85,
        backgroundColor: 'white',
        borderRadius: 25,
        height: 30,
        justifyContent: 'space-between',
        paddingRight: 10,
        flexDirection: 'row',
        alignItems: 'center',
        marginTop: 20,
    },
    firstbox: {
        width: '90%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: 30,
        justifyContent: 'space-between',
        flexDirection: 'column',
        alignItems: 'center',
    },
    secondbox: {
        width: '95%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: '55%',
        justifyContent: 'space-around',
        flexDirection: 'column',
        alignItems: 'center',
    },
    thirdbox: {
        width: '90%',
        backgroundColor: 'white',
        borderRadius: 25,
        height: '20%',
        justifyContent: 'space-between',
        flexDirection: 'row',
        alignItems: 'center',
    },
    firsttext: {
        textAlign: 'center',
        fontSize: 24,
        fontWeight: '700',
        color: '#11053b',
        lineHeight: 30,
        fontFamily: 'inter-Medium',
    },
    secondtext: {
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '600',
        lineHeight: 30,
        fontFamily: 'inter-Medium',
    },
    circle: {
        width: 40,
        backgroundColor: '#11053b',
        borderRadius: 25,
        height: 12,
    },
    circlea: {
        width: 12,
        backgroundColor: 'grey',
        borderRadius: 25,
        height: 12,
    },
    circleb: {
        width: 12,
        backgroundColor: 'grey',
        borderRadius: 25,
        height: 12,
    },
});
